### ISSUE TITLE
integration with Yao.jl

### ISSUE THREAD

**Issue by Roger-luo** [GTorlai/PastaQ.jl#120]
This is a very nice package, I'm not sure if this is what @mtfishman mentioned in JuliaCon, but just to file an issue as a backlog. 

I notice the current implementation use a rather simple circuit representation, so would be nice to integrate with [YaoBlocks](https://github.com/QuantumBFS/YaoBlocks.jl) which has tons of implemented quantum algorithms built on it, so then you should be able to run these algorithms using this PastaQ as well.

In the future, might also be nice to let [YaoLang](https://github.com/QuantumBFS/YaoLang.jl) support this as a compile target. So let me know if you are interested or need my help on this.

Bests
Roger

**Comment by mtfishman** [comment]
Hi Roger,

Thanks for reaching out. Yes, this is the package I was talking about at JuliaCon.

Indeed, the package has very few built-in quantum circuits/quantum algorithms (really just a random circuit and recently QFT). It would be interesting to look into YaoBlocks to see what is available there and how easily we could make use of it. Are there examples or documentation for how it is used?

Thanks,
Matt

**Comment by Roger-luo** [comment]
actually I just realize this is simpler than I thought! here is a demo of defining

https://github.com/GTorlai/PastaQ.jl/blob/8cdd6cd76b56172628752d812f5717e4ab94e510/src/circuits/circuits.jl#L150

in Yao

```julia
A(i, j) = control(i, j=>shift(2π/(1<<(i-j+1))))
B(n, k) = chain(n, j==k ? put(k=>H) : A(j, k) for j in k:n)
qft(n) = chain(B(n, k) for k in 1:n)
```

now when you run Yao's `qft(4)` it gives you an equivalent representation to the list you generate here. But it is organized in a tree (so called AST), we have define methods about how to execute the compositions, thus you only need to define how primitives are executed:

so let's start with defining a custom register for PastaQ

```julia
using YaoBase
struct PastaQReg{State <: Union{MPS, MPO}} <: AbstractRegister
    state::State
    # there might be some other meta info
    # but I just ignore them for now
end
```

then define how certain gates are applied to this register

```julia
instruct!(r::PastaQReg, gate::Val{:X}, locs::Tuple{N, Int}) where N = # how you apply an X gate to the MPS/MPO at locations given by the tuple locs
instruct!(r::PastaQReg, gate::Val{:X}, locs::Tuple{N, Int}, control_locs::NTuple{C, Int}, control_bits::NTuple{C, Int}) where {N, C} where N = # how you apply a controlled X gate to the MPS/MPO
```

**Comment by Roger-luo** [comment]
then when you call `Yao.apply!(register::PastaQReg, circuit)` it will find out which `instruct!` to execute and dispatch it to PastaQ methods. This should at least work for simple quantum circuit cases, for quantum channels, I think we eventually need to move to YaoLang's IR which is designed for hybrid programs.

**Comment by Roger-luo** [comment]
@mtfishman I'd like to revive this since now we are participating UnitaryHack: https://github.com/unitaryfund/unitaryhack
I can list this as an issue first, and to further develop the integration, I can submit a proposal to https://julialang.org/jsoc/#summer_2021_open_source_promotion_plan which we still have some slots to get students (by May 14th I think)

I think the first step integration should be fairly easy and can be a UnitaryHack task, the benefit of the integration would save you a lot of extra work I believe such as #200, #201 etc. and since we just start integrating JuliaQX: https://github.com/JuliaQX/YaoQX.jl I think in near future you can get a native distributed tensor network backend too. 

Thus I'm wondering if you would like to co-mentor the project so we can get some students or contributors to work on it since I assume neither you and I have enough time at the moment.

The core idea is here is to build around the new YaoIR around YaoCompiler which supports more advanced compilation techniques.

**Comment by Roger-luo** [comment]
@mtfishman close this in favor of https://github.com/QuantumBFS/YaoPastaQ.jl

**Comment by Roger-luo** [comment]
FYI, you shouldn't need to implement #200 #201 anymore now, they are or will be supported by Yao.
