### ISSUE TITLE
Introduce `invcircuit` and `dagcircuit` functions

### ISSUE THREAD

**Issue by mtfishman** [GTorlai/PastaQ.jl#139]
Introduce the `dagcircuit` function, which does the following:
```julia
gates = [("Rx", 1, (θ = π/4,)),
         ("Ry", 2, (θ = π/4,))]

dagcircuit(gates)
```
returns the gate list:
```julia
 ("Ry", 2, (θ = 0.7853981633974483, dag = true))
 ("Rx", 1, (θ = 0.7853981633974483, dag = true))
```
i.e. it reverses the gate list ordering and adds the `dag = true` keyword argument. Then, the `gate` function can be generalized to recognize the `dag` flag, and perform the conjugate transpose of the gate when the ITensor is made.

Similarly, an `invcircuit` function could be defined which instead adds the flag `inv = true`, which could work for nonunitary gates.

**Comment by GTorlai** [comment]
The `dag` part has been done, I'm closing this for now and re-open in the future if we actually need the `inv`
