### ISSUE TITLE
Determine number of sites automatically in runcircuit/getsamples

### ISSUE THREAD

**Issue by mtfishman** [GTorlai/PastaQ.jl#142]
In `runcircuit`/`getsamples`, in calls like `runcircuit(N, gates)`, in theory the number of sites `N` could be determined automatically by searching through the gate list for the largest site that is found. Therefore we could make inputting `N` optional (there may be times when you still want to specify `N`, like if you don't have gates on your entire system).

**Comment by GTorlai** [comment]
Good idea. And yes, we should leave the option to input `N` if there are spectator qubits.
