### ISSUE TITLE
Error in examples test making random circuits

### ISSUE THREAD

**Issue by mtfishman** [GTorlai/PastaQ.jl#194]
https://github.com/GTorlai/PastaQ.jl/blob/afcc5af3f089cb249293bd90414332a8986a735e/test/utils.jl#L84-L104

**Comment by mtfishman** [comment]
This randomly errors (maybe related to using even or odd sites).

**Comment by GTorlai** [comment]
This is related to circuit containing only 2 qubits, since there are only one possible two-qubit gate you can apply (in contrast with even-odd pattern for N>3).
