### ISSUE TITLE
Resolve index ordering in QPT gradients

### ISSUE THREAD

**Issue by GTorlai** [GTorlai/PastaQ.jl#233]
The index ordering (which is usually not an issue) creates some clashing when using the optimizer to update a variational tensor network. This is cause by transforming the variational tensors into dense arrays to be passed to the optimizers, with the problem being the gradients and the model not having the same ordering, thus resulting into updating the wrong tensor elements.

**Comment by mtfishman** [comment]
Could you explain the issue in a bit more detail? Is this particular to the Flux optimizers?
