### ISSUE TITLE
How to calculate the entropy/entanglement metrics efficiently

### ISSUE THREAD

**Issue by Mi-Peng** [GTorlai/PastaQ.jl#307]
Thanks for this awesome work. I'm wondering if PastaQ provides API to calculate the entropy and other entanglement metrics efficiently, or they are calculated manually, e.g., using eigenvalues to calculate von Neumann entropy, which is considered time-consuming when q-bit is large. Thanks.

**Comment by mtfishman** [comment]
I would take a look at the ITensor discussion forum (https://itensor.discourse.group/) and ask a question there if your question isn't answered in one of the posts already.

**Comment by mtfishman** [comment]
I'm closing since I think this is more of a user support question, and that functionality is outside of the scope of this package (we may add more convenient functions for how to do that in ITensor, that functionality probably would not go here).
