### ISSUE TITLE
Automatic generation of measurements/preparation gates

### ISSUE THREAD

**Issue by GTorlai** [GTorlai/PastaQ.jl#66]
Ideally we would like to have an automated way to generate the various gates for preparation and measurement rotations. 

- Preparation gates
Given a set of specified single-qubit states (ψ1,…ψK), we generate a set of gates (g1,…,gK) generating each state.

- Measurement bases
For each measurement basis (given as input as a hermitian 2x2 matrix), we generate the gate for the corresponding rotation.

**Comment by mtfishman** [comment]
Closed by #136. For now, preparation gates have been removed, they can be added back when preparation errors are introduced.
